### ISSUE TITLE
CLI not working??

### ISSUE THREAD

**Issue by Joshfairhead** [hack-along/gridsome-boilerplate#1]
Trying the command `gridsome develop` I get `unknown command develop`. Is this a feature (because it's a boiler plate) or a bug?

Thanks!

**Comment by MGrudule** [comment]
Hei Josh,
Just tried clone/install and can't reproduce the issue.

Just in case updated the readme to reflect the exact steps required. Can you try it out again following those steps and report if you still are experiencing any issues? 

For now, my best guess is that you were trying to run the script from the wrong directory.

you can quickly reference any scripts a project is using by  reading the [package.json](https://github.com/hack-along/gridsome-boilerplate/blob/master/package.json) file

```
 "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
```

I hope this helps!

**Comment by Joshfairhead** [comment]
This was the error: ![Screenshot 2020-06-08 at 16 36 42](https://user-images.githubusercontent.com/34649155/84043262-5ab99b00-a9a6-11ea-8680-5f1d7fd6a373.png)

But yeah, nailed it - I didn't `npm install` so the `gridsome develop` command didn't work... it does now - much appreciated! :)

**Comment by MGrudule** [comment]
Good to hear
